### ISSUE TITLE
Issue dealing with 503 responses from S3

### ISSUE THREAD

**Issue by tyro89** [memsql/memsql-loader#14]
We have just run into an issue with a 500mb file downloading from S3 as a 282 byte file and resulting in a empty-row in our db. From our explorations it looks like S3 might have responded to the download request with a 503 - SlowDown. Looking through the memsql-loader code it seems like status codes >= 500 are unhandled:

    curl.perform()
    status_code = curl.getinfo(pycurl.HTTP_CODE)
    # Catch HTTP client errors, e.g. 404:
    if status_code >= 400 and status_code < 500:
        raise WorkerException('HTTP status code %s for file %s' % (status_code, self.key.name))

in addition, pycurl seems to be running with the default `FAILONERROR=false` which could result in a 503 slipping by unnoticed.

We're wondering if our assessment here is correct, i.e. is it possible for a 503 to slip by unnoticed or is it actually handled?

If it is an issue we're also wondering if a simple fix to error on any non-200 status codes would be acceptable? Ideally a 503 - SlowDown should be handled gracefully by a backoff-and-retry but that seems like fair bit of work. In the short term failing on any non-200 status codes seems like a easy to implement and safer behaviour.

**Comment by carlsverre** [comment]
@tyro89 Thanks for bringing this to our attention - it appears you have found a bug.  I am trying to track down the initial commit from before we made this project open source that introduced this issue.  Super weird that we are explicitly ignoring 500+ errors seeing as we obviously don't want to load in the event of server error.

We will release a new version of loader that fails for any error code over 400 rather than just between 400 and 500.  I believe this is the safest change.  If you are interested in building 503 specific backoff behavior feel free to send a pull request.

Thanks!

**Comment by tyro89** [comment]
Awesome! Thanks for the quick response and fix @carlsverre ! :)

**Comment by carlsverre** [comment]
Released: https://github.com/memsql/memsql-loader/releases/tag/2.0.5

Also will upload to Pypi soon

**Comment by carlsverre** [comment]
Whoops - forgot we removed that install method.  You should be good to go with the uploaded binary release.

Good luck!
