### ISSUE TITLE
Issue with task cancellation

### ISSUE THREAD

**Issue by tyro89** [memsql/memsql-loader#16]
We are loading a single gigantic file into memsql from s3 and in certain circumstances the network latencies do not make it possible for us to fetch the file under `TASKS_TTL` (120s). This in turn triggers a task re-queue with a log entry

    (INFO) Task 2: finished with error, the task was either cancelled or deleted

The problem with this is that it seems like one of the following is happening:

- the downloader/loader threads are not cancelled appropriately
- the loader connections are not rollbacked
- the loader connections are not transactional

We are not sure which of these situation is occurring but what we do know is that we end up with duplicate data for every row in our table (i.e. the table is effectively loaded twice).

We can get around this by splitting our file but it is still a little problematic that there is a `120s` hardcoded task limit that can cause unsafe task cancellations. With smaller files we are less likely to run into the `120s` limit but under bad network situations it might still occur. Plus, if only a part of the dataset is loaded twice it is going to be a much sneakier bug 😢

**Comment by carlsverre** [comment]
Tyro, sorry to hear you are having these issues.  Luckily I know the underlying bug and we have some options for a fix.

The bug is that once memsql-loader calls COMMIT on the transaction - MemSQL is guaranteed to commit the transaction atomically.  This unfortunately is true EVEN in the event that the connection running the COMMIT is cancelled (which is what happens on timeout).

To fix the issue we can do one or both of these things:

1. Make the timeout configurable - this will take very little time and will result in you being unblocked for the time being
2. If we error while the COMMIT query is running, we need to raise a WorkerException so the task does not requeue

I will file the above tasks so we can hopefully get them resolved soon (or feel free to submit pull reqs, happy to test them on my side)

**Comment by tyro89** [comment]
Thanks for the quick response! Both of your suggestions sounds like great improvements! 👍
